# Generated by Django 5.0.2 on 2024-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="titlr",
            new_name="title",
        ),
        migrations.AddField(
            model_name="post",
            name="country",
            field=models.CharField(default="", max_length=30),
        ),
    ]
