# Generated by Django 5.0.2 on 2024-03-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_titlr_post_title_post_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("drf", "Draft"), ("pud", "Published")],
                default="drf",
                max_length=3,
            ),
        ),
    ]
